version: "3.2"

services:
  apigateway:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ApiGateway
    depends_on:
      - rabbitmq
      - mongodb
    ports:
      - "5000:5000"
    volumes:
      - ./backend_service/logs:/usr/src/app/logs
      - /mnt/efs:/mnt/efs
    command: npm start
    networks:
      softlaser_v2_net:
        ipv4_address: 144.33.111.11

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      devops:

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  devops:
    ipam:
      driver: default
      config:
        - subnet: 32.33.111.0/24

volumes:
  mongodb_data: